export const skillsData = {
  Languages: [
    { name: 'C', icon: 'devicon-c-plain' },
    { name: 'C++', icon: 'devicon-cplusplus-plain' },
    { name: 'C#', icon: 'devicon-csharp-plain' },
    { name: 'Go', icon: 'devicon-go-plain' },
    { name: 'Java', icon: 'devicon-java-plain' },
    { name: 'JavaScript', icon: 'devicon-javascript-plain' },
    { name: 'TypeScript', icon: 'devicon-typescript-plain' },
    { name: 'PHP', icon: 'devicon-php-plain' },
    { name: 'Perl', icon: 'devicon-perl-plain' },
    { name: 'Ruby', icon: 'devicon-ruby-plain' },
    { name: 'Scala', icon: 'devicon-scala-plain' },
    { name: 'Python', icon: 'devicon-python-plain' },
    { name: 'Swift', icon: 'devicon-swift-plain' },
    { name: 'Objective-C', icon: 'devicon-objectivec-plain' },
    { name: 'Clojure', icon: 'devicon-clojure-plain' },
    { name: 'Rust', icon: 'devicon-rust-plain' },
    { name: 'Haskell', icon: 'devicon-haskell-plain' },
    { name: 'CoffeeScript', icon: 'devicon-coffeescript-plain' },
    { name: 'Elixir', icon: 'devicon-elixir-plain' },
    { name: 'Erlang', icon: 'devicon-erlang-plain' },
    { name: 'Nim', icon: 'devicon-nim-plain' },
  ],
  'Frontend Development': [
    { name: 'Vue.js', icon: 'devicon-vuejs-plain' },
    { name: 'React', icon: 'devicon-react-plain' },
    { name: 'Svelte', icon: 'devicon-svelte-plain' },
    { name: 'AngularJS', icon: 'devicon-angularjs-plain' },
    { name: 'Angular', icon: 'devicon-angular-plain' },
    { name: 'Backbone.js', icon: 'devicon-backbonejs-plain' },
    { name: 'Bootstrap', icon: 'devicon-bootstrap-plain' },
    { name: 'Vuetify', icon: 'devicon-vuetify-plain' },
    { name: 'CSS3', icon: 'devicon-css3-plain' },
    { name: 'HTML5', icon: 'devicon-html5-plain' },
    { name: 'Pug', icon: 'devicon-pug-plain' },
    { name: 'Gulp', icon: 'devicon-gulp-plain' },
    { name: 'Sass', icon: 'devicon-sass-plain' },
    { name: 'Redux', icon: 'devicon-redux-plain' },
    { name: 'Webpack', icon: 'devicon-webpack-plain' },
    { name: 'Babel', icon: 'devicon-babel-plain' },
    { name: 'Tailwind CSS', icon: 'devicon-tailwindcss-plain' },
    { name: 'Materialize', icon: 'devicon-materializecss-plain' },
    { name: 'Bulma', icon: 'devicon-bulma-plain' },
    { name: 'GTK', icon: 'devicon-gtk-plain' },
    { name: 'Qt', icon: 'devicon-qt-plain' },
    { name: 'wxWidgets', icon: 'devicon-wxwidgets-plain' },
    { name: 'Ember', icon: 'devicon-ember-plain' },
  ],
  'Backend Development': [
    { name: 'Node.js', icon: 'devicon-nodejs-plain' },
    { name: 'Spring', icon: 'devicon-spring-plain' },
    { name: 'Express', icon: 'devicon-express-original' },
    { name: 'GraphQL', icon: 'devicon-graphql-plain' },
    { name: 'Kafka', icon: 'devicon-apachekafka-plain' },
    { name: 'Solr', icon: 'devicon-solr-plain' },
    { name: 'RabbitMQ', icon: 'devicon-rabbitmq-plain' },
    { name: 'Hadoop', icon: 'devicon-hadoop-plain' },
    { name: 'Nginx', icon: 'devicon-nginx-plain' },
    { name: 'OpenResty', icon: 'devicon-openresty-plain' },
    { name: 'NestJS', icon: 'devicon-nestjs-plain' },
  ],
  'Mobile App Development': [
    { name: 'Android', icon: 'devicon-android-plain' },
    { name: 'Flutter', icon: 'devicon-flutter-plain' },
    { name: 'Dart', icon: 'devicon-dart-plain' },
    { name: 'Kotlin', icon: 'devicon-kotlin-plain' },
    { name: 'NativeScript', icon: 'devicon-nativescript-plain' },
    { name: 'Xamarin', icon: 'devicon-xamarin-plain' },
    { name: 'React Native', icon: 'devicon-react-plain' },
    { name: 'Ionic', icon: 'devicon-ionic-plain' },
    { name: 'Apache Cordova', icon: 'devicon-cordova-plain' },
  ],
  'AI/ML': [
    { name: 'TensorFlow', icon: 'devicon-tensorflow-original' },
    { name: 'PyTorch', icon: 'devicon-pytorch-original' },
    { name: 'Pandas', icon: 'devicon-pandas-original' },
    { name: 'Seaborn', icon: 'devicon-seaborn-original' },
    { name: 'OpenCV', icon: 'devicon-opencv-plain' },
    { name: 'Scikit-learn', icon: 'devicon-scikitlearn-plain' },
  ],
  Database: [
    { name: 'MongoDB', icon: 'devicon-mongodb-plain' },
    { name: 'MySQL', icon: 'devicon-mysql-plain' },
    { name: 'PostgreSQL', icon: 'devicon-postgresql-plain' },
    { name: 'Redis', icon: 'devicon-redis-plain' },
    { name: 'Oracle', icon: 'devicon-oracle-original' },
    { name: 'Cassandra', icon: 'devicon-cassandra-plain' },
    { name: 'CouchDB', icon: 'devicon-couchdb-plain' },
    { name: 'Hive', icon: 'devicon-apachehive-plain' },
    { name: 'Realm', icon: 'devicon-realm-plain' },
    { name: 'MariaDB', icon: 'devicon-mariadb-plain' },
    { name: 'CockroachDB', icon: 'devicon-cockroachdb-plain' },
    { name: 'Elasticsearch', icon: 'devicon-elasticsearch-plain' },
    { name: 'SQLite', icon: 'devicon-sqlite-plain' },
    { name: 'MSSQL', icon: 'devicon-microsoftsqlserver-plain' },
  ],
  'Data Visualization': [
    { name: 'D3.js', icon: 'devicon-d3js-plain' },
    { name: 'Chart.js', icon: 'devicon-chartjs-plain' },
    { name: 'CanvasJS', icon: 'devicon-canvasjs-plain' },
    { name: 'Kibana', icon: 'devicon-kibana-plain' },
    { name: 'Grafana', icon: 'devicon-grafana-plain' },
  ],
  DevOps: [
    { name: 'AWS', icon: 'devicon-amazonwebservices-original' },
    { name: 'Docker', icon: 'devicon-docker-plain' },
    { name: 'Jenkins', icon: 'devicon-jenkins-plain' },
    { name: 'GCP', icon: 'devicon-googlecloud-plain' },
    { name: 'Kubernetes', icon: 'devicon-kubernetes-plain' },
    { name: 'Bash', icon: 'devicon-bash-plain' },
    { name: 'Azure', icon: 'devicon-azure-plain' },
    { name: 'Vagrant', icon: 'devicon-vagrant-plain' },
    { name: 'CircleCI', icon: 'devicon-circleci-plain' },
    { name: 'Travis CI', icon: 'devicon-travis-plain' },
  ],
  'Backend as a Service (BaaS)': [
    { name: 'Firebase', icon: 'devicon-firebase-plain' },
    { name: 'Appwrite', icon: 'devicon-appwrite-plain' },
    ]
}
